import WelcomeCard from '../components/WelcomCard'
import AboutMe from '../components/AboutMe'
// import Carrucel from '../components/Carrucel'
// import imageData from '../components/data'
import Skills from '../components/ProgressSkils'

export default function HomePage () {
  return (
    <div>
      <WelcomeCard />
      <AboutMe />
      <Skills />
      {/* <Carrucel images={imageData} /> */}
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae et id consequatur distinctio, sed facere nisi similique cumque quos odit. Temporibus neque expedita eaque ipsa labore officiis maxime odio tenetur eius corrupti hic deserunt id reiciendis inventore, error nihil optio! Rem, optio? Inventore doloremque labore sit deleniti odit exercitationem consectetur ea quos quasi modi quisquam quis adipisci, laboriosam tempora eveniet reprehenderit minima, id libero. Deleniti accusantium molestiae doloremque, rem at excepturi laborum sit maiores nostrum facilis commodi ipsum minus tempora blanditiis non vel dolorem odit laboriosam quas voluptas laudantium harum ab eaque. Sed accusantium odit velit excepturi. Quia maiores hic, officia reiciendis a suscipit animi nesciunt, voluptatum quam, perferendis possimus est eius ipsa cupiditate non? Necessitatibus, nisi. Corporis adipisci nostrum beatae voluptatibus itaque cum aspernatur ad, consequatur minima. Culpa, veritatis possimus. Pariatur quae temporibus at nihil dolores veniam amet quia magnam, ab voluptatum praesentium unde dolorem rem ipsa blanditiis, quam esse reiciendis consequuntur saepe? Culpa cupiditate vero quo placeat veritatis error minima quisquam molestias numquam cumque, ratione soluta quis voluptatibus itaque suscipit fugit eum hic illum? Nihil, beatae rerum corrupti repellat tenetur amet labore adipisci illo quia quae possimus, at ut itaque autem doloremque excepturi, necessitatibus recusandae reiciendis? Mollitia, assumenda.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae et id consequatur distinctio, sed facere nisi similique cumque quos odit. Temporibus neque expedita eaque ipsa labore officiis maxime odio tenetur eius corrupti hic deserunt id reiciendis inventore, error nihil optio! Rem, optio? Inventore doloremque labore sit deleniti odit exercitationem consectetur ea quos quasi modi quisquam quis adipisci, laboriosam tempora eveniet reprehenderit minima, id libero. Deleniti accusantium molestiae doloremque, rem at excepturi laborum sit maiores nostrum facilis commodi ipsum minus tempora blanditiis non vel dolorem odit laboriosam quas voluptas laudantium harum ab eaque. Sed accusantium odit velit excepturi. Quia maiores hic, officia reiciendis a suscipit animi nesciunt, voluptatum quam, perferendis possimus est eius ipsa cupiditate non? Necessitatibus, nisi. Corporis adipisci nostrum beatae voluptatibus itaque cum aspernatur ad, consequatur minima. Culpa, veritatis possimus. Pariatur quae temporibus at nihil dolores veniam amet quia magnam, ab voluptatum praesentium unde dolorem rem ipsa blanditiis, quam esse reiciendis consequuntur saepe? Culpa cupiditate vero quo placeat veritatis error minima quisquam molestias numquam cumque, ratione soluta quis voluptatibus itaque suscipit fugit eum hic illum? Nihil, beatae rerum corrupti repellat tenetur amet labore adipisci illo quia quae possimus, at ut itaque autem doloremque excepturi, necessitatibus recusandae reiciendis? Mollitia, assumenda.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae et id consequatur distinctio, sed facere nisi similique cumque quos odit. Temporibus neque expedita eaque ipsa labore officiis maxime odio tenetur eius corrupti hic deserunt id reiciendis inventore, error nihil optio! Rem, optio? Inventore doloremque labore sit deleniti odit exercitationem consectetur ea quos quasi modi quisquam quis adipisci, laboriosam tempora eveniet reprehenderit minima, id libero. Deleniti accusantium molestiae doloremque, rem at excepturi laborum sit maiores nostrum facilis commodi ipsum minus tempora blanditiis non vel dolorem odit laboriosam quas voluptas laudantium harum ab eaque. Sed accusantium odit velit excepturi. Quia maiores hic, officia reiciendis a suscipit animi nesciunt, voluptatum quam, perferendis possimus est eius ipsa cupiditate non? Necessitatibus, nisi. Corporis adipisci nostrum beatae voluptatibus itaque cum aspernatur ad, consequatur minima. Culpa, veritatis possimus. Pariatur quae temporibus at nihil dolores veniam amet quia magnam, ab voluptatum praesentium unde dolorem rem ipsa blanditiis, quam esse reiciendis consequuntur saepe? Culpa cupiditate vero quo placeat veritatis error minima quisquam molestias numquam cumque, ratione soluta quis voluptatibus itaque suscipit fugit eum hic illum? Nihil, beatae rerum corrupti repellat tenetur amet labore adipisci illo quia quae possimus, at ut itaque autem doloremque excepturi, necessitatibus recusandae reiciendis? Mollitia, assumenda.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae et id consequatur distinctio, sed facere nisi similique cumque quos odit. Temporibus neque expedita eaque ipsa labore officiis maxime odio tenetur eius corrupti hic deserunt id reiciendis inventore, error nihil optio! Rem, optio? Inventore doloremque labore sit deleniti odit exercitationem consectetur ea quos quasi modi quisquam quis adipisci, laboriosam tempora eveniet reprehenderit minima, id libero. Deleniti accusantium molestiae doloremque, rem at excepturi laborum sit maiores nostrum facilis commodi ipsum minus tempora blanditiis non vel dolorem odit laboriosam quas voluptas laudantium harum ab eaque. Sed accusantium odit velit excepturi. Quia maiores hic, officia reiciendis a suscipit animi nesciunt, voluptatum quam, perferendis possimus est eius ipsa cupiditate non? Necessitatibus, nisi. Corporis adipisci nostrum beatae voluptatibus itaque cum aspernatur ad, consequatur minima. Culpa, veritatis possimus. Pariatur quae temporibus at nihil dolores veniam amet quia magnam, ab voluptatum praesentium unde dolorem rem ipsa blanditiis, quam esse reiciendis consequuntur saepe? Culpa cupiditate vero quo placeat veritatis error minima quisquam molestias numquam cumque, ratione soluta quis voluptatibus itaque suscipit fugit eum hic illum? Nihil, beatae rerum corrupti repellat tenetur amet labore adipisci illo quia quae possimus, at ut itaque autem doloremque excepturi, necessitatibus recusandae reiciendis? Mollitia, assumenda.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae et id consequatur distinctio, sed facere nisi similique cumque quos odit. Temporibus neque expedita eaque ipsa labore officiis maxime odio tenetur eius corrupti hic deserunt id reiciendis inventore, error nihil optio! Rem, optio? Inventore doloremque labore sit deleniti odit exercitationem consectetur ea quos quasi modi quisquam quis adipisci, laboriosam tempora eveniet reprehenderit minima, id libero. Deleniti accusantium molestiae doloremque, rem at excepturi laborum sit maiores nostrum facilis commodi ipsum minus tempora blanditiis non vel dolorem odit laboriosam quas voluptas laudantium harum ab eaque. Sed accusantium odit velit excepturi. Quia maiores hic, officia reiciendis a suscipit animi nesciunt, voluptatum quam, perferendis possimus est eius ipsa cupiditate non? Necessitatibus, nisi. Corporis adipisci nostrum beatae voluptatibus itaque cum aspernatur ad, consequatur minima. Culpa, veritatis possimus. Pariatur quae temporibus at nihil dolores veniam amet quia magnam, ab voluptatum praesentium unde dolorem rem ipsa blanditiis, quam esse reiciendis consequuntur saepe? Culpa cupiditate vero quo placeat veritatis error minima quisquam molestias numquam cumque, ratione soluta quis voluptatibus itaque suscipit fugit eum hic illum? Nihil, beatae rerum corrupti repellat tenetur amet labore adipisci illo quia quae possimus, at ut itaque autem doloremque excepturi, necessitatibus recusandae reiciendis? Mollitia, assumenda.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae et id consequatur distinctio, sed facere nisi similique cumque quos odit. Temporibus neque expedita eaque ipsa labore officiis maxime odio tenetur eius corrupti hic deserunt id reiciendis inventore, error nihil optio! Rem, optio? Inventore doloremque labore sit deleniti odit exercitationem consectetur ea quos quasi modi quisquam quis adipisci, laboriosam tempora eveniet reprehenderit minima, id libero. Deleniti accusantium molestiae doloremque, rem at excepturi laborum sit maiores nostrum facilis commodi ipsum minus tempora blanditiis non vel dolorem odit laboriosam quas voluptas laudantium harum ab eaque. Sed accusantium odit velit excepturi. Quia maiores hic, officia reiciendis a suscipit animi nesciunt, voluptatum quam, perferendis possimus est eius ipsa cupiditate non? Necessitatibus, nisi. Corporis adipisci nostrum beatae voluptatibus itaque cum aspernatur ad, consequatur minima. Culpa, veritatis possimus. Pariatur quae temporibus at nihil dolores veniam amet quia magnam, ab voluptatum praesentium unde dolorem rem ipsa blanditiis, quam esse reiciendis consequuntur saepe? Culpa cupiditate vero quo placeat veritatis error minima quisquam molestias numquam cumque, ratione soluta quis voluptatibus itaque suscipit fugit eum hic illum? Nihil, beatae rerum corrupti repellat tenetur amet labore adipisci illo quia quae possimus, at ut itaque autem doloremque excepturi, necessitatibus recusandae reiciendis? Mollitia, assumenda.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae et id consequatur distinctio, sed facere nisi similique cumque quos odit. Temporibus neque expedita eaque ipsa labore officiis maxime odio tenetur eius corrupti hic deserunt id reiciendis inventore, error nihil optio! Rem, optio? Inventore doloremque labore sit deleniti odit exercitationem consectetur ea quos quasi modi quisquam quis adipisci, laboriosam tempora eveniet reprehenderit minima, id libero. Deleniti accusantium molestiae doloremque, rem at excepturi laborum sit maiores nostrum facilis commodi ipsum minus tempora blanditiis non vel dolorem odit laboriosam quas voluptas laudantium harum ab eaque. Sed accusantium odit velit excepturi. Quia maiores hic, officia reiciendis a suscipit animi nesciunt, voluptatum quam, perferendis possimus est eius ipsa cupiditate non? Necessitatibus, nisi. Corporis adipisci nostrum beatae voluptatibus itaque cum aspernatur ad, consequatur minima. Culpa, veritatis possimus. Pariatur quae temporibus at nihil dolores veniam amet quia magnam, ab voluptatum praesentium unde dolorem rem ipsa blanditiis, quam esse reiciendis consequuntur saepe? Culpa cupiditate vero quo placeat veritatis error minima quisquam molestias numquam cumque, ratione soluta quis voluptatibus itaque suscipit fugit eum hic illum? Nihil, beatae rerum corrupti repellat tenetur amet labore adipisci illo quia quae possimus, at ut itaque autem doloremque excepturi, necessitatibus recusandae reiciendis? Mollitia, assumenda.</p>
    </div>
  )
}
